2022-02-01 12:18:25,052 - ERROR - baseApi.py[60]:Traceback (most recent call last):
  File "D:\AutoTextAPI\commcon\baseApi.py", line 53, in define_api_assert
    assert result == exp_result
AssertionError

